SELECT 
T1.ORIGINATOR,
T1.VA AS LEAD_VA, 
T1.CA AS LEAD_CA, 
CASE WHEN ISNUMERIC(T2.ALASKA_VA) = 1 THEN CAST(T2.ALASKA_VA AS INT) ELSE T2.ALASKA_CA END AS ALASKA_VA,
CASE WHEN ISNUMERIC(T2.ALASKA_CA) = 1 THEN CAST(T2.ALASKA_CA AS INT) ELSE T2.ALASKA_CA END AS ALASKA_CA,
T2.DESCRIPTION, 
DATEFROMPARTS('20'+ RIGHT(T2.START_DT,2), LEFT(T2.START_DT,2), LEFT(RIGHT(T2.START_DT,4),2)) AS START_DT,
DATEFROMPARTS('20'+ RIGHT(T2.END_DT,2), LEFT(T2.END_DT,2), LEFT(RIGHT(T2.END_DT,4),2)) AS END_DT,
T1.IEA,
T1.SPEC_CODE, 
T1.SPEC, 
T1.ELIGIBILITY_TYPE,
T2.SEATTLE_DIST, 
CAST(T1.TIMESTAMP AS DATE) AS TIMESTAMP

FROM ALASKA_CUSTOMER_ELIGIBILITY AS T1

INNER JOIN ALASKA_HEADER AS T2 
ON T1.VA = T2.VA
AND T1.CA = T2.CA

WHERE T1.TIMESTAMP = CAST(DATEADD(day, -1, GETDATE()) AS DATE)
AND T2.CHANGE_CODE = 'NEW'

ORDER BY 
LEAD_VA, 
LEAD_CA, 
IEA, 
SPEC_CODE, 
SPEC