SELECT DISTINCT 
T2.ORIGINATOR,
T1.VA AS LEAD_VA, 
T1.CA AS LEAD_CA, 
CASE WHEN ISNUMERIC(T1.ALASKA_VA) = 1 THEN CAST(T1.ALASKA_VA AS INT) ELSE T1.ALASKA_CA END AS ALASKA_VA,
CASE WHEN ISNUMERIC(T1.ALASKA_CA) = 1 THEN CAST(T1.ALASKA_CA AS INT) ELSE T1.ALASKA_CA END AS ALASKA_CA,
T1.VENDOR_NBR,
T1.DESCRIPTION, 
DATEFROMPARTS('20'+ RIGHT(T1.START_DT,2), LEFT(T1.START_DT,2), LEFT(RIGHT(T1.START_DT,4),2)) AS START_DT,
DATEFROMPARTS('20'+ RIGHT(T1.END_DT,2), LEFT(T1.END_DT,2), LEFT(RIGHT(T1.END_DT,4),2)) AS END_DT,
T1.VA_TYPE,
T1.CA_TYPE, 
T1.COST_BASIS,
T1.ALASKA_COST_BASIS,
T1.REBATE_TYPE, 
T1.PAST_DUE_DEDUCT, 
T1.BILLBACK_FORMAT,
T1.CORP_CLAIMED,
T1.APPROP_NAME,
T2.ELIGIBILITY_TYPE,
T1.SEATTLE_DIST, 
CAST(T1.TIMESTAMP AS DATE) AS TIMESTAMP

FROM Alaska_Header AS T1

INNER JOIN ALASKA_CUSTOMER_ELIGIBILITY AS T2
ON T1.VA = T2.VA
AND T1.CA = T2.CA

WHERE T1.TIMESTAMP = CAST(DATEADD(day, -1, GETDATE()) AS DATE)
AND T1.CHANGE_CODE = 'NEW'

ORDER BY 
LEAD_VA, 
LEAD_CA