SELECT DISTINCT 
T2.ORIGINATOR,
T1.VA AS LEAD_VA, 
T1.CA AS LEAD_CA, 
CASE WHEN ISNUMERIC(T3.ALASKA_VA) = 1 THEN CAST(T3.ALASKA_VA AS INT) ELSE T3.ALASKA_CA END AS ALASKA_VA,
CASE WHEN ISNUMERIC(T3.ALASKA_CA) = 1 THEN CAST(T3.ALASKA_CA AS INT) ELSE T3.ALASKA_CA END AS ALASKA_CA,
T3.DESCRIPTION, 
DATEFROMPARTS('20'+ RIGHT(T3.START_DT,2), LEFT(T3.START_DT,2), LEFT(RIGHT(T3.START_DT,4),2)) AS START_DT,
DATEFROMPARTS('20'+ RIGHT(T3.END_DT,2), LEFT(T3.END_DT,2), LEFT(RIGHT(T3.END_DT,4),2)) AS END_DT,
T1.IEA, 
T1.SPEC_CD AS SPEC_CODE, 
T1.ITEM, 
T1.VA_REBATE_BASIS, 
T1.VA_REBATE_AMT, 
T1.VA_ALASKA_AMT, 
T1.VA_APPROP_AMT, 
T1.CA_REBATE_BASIS, 
T1.CA_ALLOWANCE, 
T1.CA_COMM_BASE, 
T1.CA_ADJ_AP, 
T1.CA_ALASKA_ADJ_AP, 
T1.SOURCE_VNDR,
T3.SEATTLE_DIST,
CAST(T1.TIMESTAMP AS DATE) AS TIMESTAMP

FROM ALASKA_ITEM_ELIGIBILITY AS T1

INNER JOIN ALASKA_CUSTOMER_ELIGIBILITY AS T2
ON T1.VA = T2.VA
AND T1.CA = T2.CA

INNER JOIN ALASKA_HEADER AS T3
ON T1.VA = T3.VA
AND T1.CA = T3.CA

WHERE T1.TIMESTAMP = CAST(DATEADD(day, -1, GETDATE()) AS DATE)
AND T3.CHANGE_CODE = 'NEW'

ORDER BY 
LEAD_VA, 
LEAD_CA, 
IEA, 
SPEC_CODE,
ITEM