SELECT 
T1.VA, 
T1.CA, 
CASE WHEN ISNUMERIC(T1.ALASKA_VA) = 1 THEN CAST(T1.ALASKA_VA AS INT) ELSE T1.ALASKA_CA END AS ALASKA_VA,
CASE WHEN ISNUMERIC(T1.ALASKA_CA) = 1 THEN CAST(T1.ALASKA_CA AS INT) ELSE T1.ALASKA_CA END AS ALASKA_CA,
T1.DESCRIPTION,
DATEFROMPARTS('20'+ RIGHT(T1.START_DT,2), LEFT(T1.START_DT,2), LEFT(RIGHT(T1.START_DT,4),2)) AS START_DT,
DATEFROMPARTS('20'+ RIGHT(T1.END_DT,2), LEFT(T1.END_DT,2), LEFT(RIGHT(T1.END_DT,4),2)) AS END_DT

FROM ALASKA_HEADER AS T1

LEFT JOIN ALASKA_HEADER AS T2
ON T1.[DESCRIPTION] = T2.[DESCRIPTION]
AND T1.VA <> T2.VA 
AND T1.CA <> T2.CA
AND DATEFROMPARTS('20'+ RIGHT(T2.END_DT,2), LEFT(T2.END_DT,2), LEFT(RIGHT(T2.END_DT,4),2)) >= GETDATE()

WHERE DATEFROMPARTS('20'+ RIGHT(T1.END_DT,2), LEFT(T1.END_DT,2), LEFT(RIGHT(T1.END_DT,4),2)) < GETDATE()
AND T2.VA IS NULL
